version: "3"
services:
  server:
    container_name: party-tonight
    image: "limyeonjy/party-tonight"
    ports:
      - "8080:8080"
    depends_on:
      - redis
    networks:
      - app-tier

networks:
  app-tier:
    driver: bridge
